#include <iostream>
#include <vector>
#include <cstdlib>
#include <ctime>

using namespace std;

int escolha;

int main(){
    switch (escolha)
    {
    case 1:
     vector<int> numeros;
     vector<int> numerossemrepeticao;
        for (int i=0; i< 20; i++){
            int numeros;
            cout << "Digite o " << i + 1 << "º número: ";
            cin  >> numeros;




        }
        break;
    case 2:
        break;
    case 3:
        break;
    case 4:
        break;
    case 5:
        break;
    case 6:
        break;

    default:
        break;
    }
return 0;
}